backend:
  name: git-gateway
  branch: master
local_backend: true
locale: de
media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow
logo_url: 'https://preview.kickstartds.com/images/logo.png'
collections:
