
import loadable from '@loadable/component';

export default {
  'button': loadable(() => import('@kickstartds/base/lib/button/index.js'), { resolveComponent: (exports) => exports.Button }),
  'content-box': loadable(() => import('@kickstartds/base/lib/content-box/index.js'), { resolveComponent: (exports) => exports.ContentBox }),
  'divider': loadable(() => import('@kickstartds/base/lib/divider/index.js'), { resolveComponent: (exports) => exports.Divider }),
  'headline': loadable(() => import('@kickstartds/base/lib/headline/index.js'), { resolveComponent: (exports) => exports.Headline }),
  'html': loadable(() => import('@kickstartds/base/lib/html/index.js'), { resolveComponent: (exports) => exports.Html }),
  'icon': loadable(() => import('@kickstartds/base/lib/icon/index.js'), { resolveComponent: (exports) => exports.Icon }),
  'iframe': loadable(() => import('@kickstartds/base/lib/iframe/index.js'), { resolveComponent: (exports) => exports.IframeRatio }),
  'lightbox': loadable(() => import('@kickstartds/base/lib/lightbox/index.js'), { resolveComponent: (exports) => exports.LightBox }),
  'lightbox-image': loadable(() => import('@kickstartds/base/lib/lightbox-image/index.js'), { resolveComponent: (exports) => exports.LightboxLazyImage }),
  'link': loadable(() => import('@kickstartds/base/lib/link/index.js'), { resolveComponent: (exports) => exports.Link }),
  'link-button': loadable(() => import('@kickstartds/base/lib/link-button/index.js'), { resolveComponent: (exports) => exports.LinkButton }),
  'logo': loadable(() => import('@kickstartds/base/lib/logo/index.js'), { resolveComponent: (exports) => exports.Logo }),
  'nav-main': loadable(() => import('@kickstartds/base/lib/nav-main/index.js'), { resolveComponent: (exports) => exports.NavMain }),
  'nav-meta': loadable(() => import('@kickstartds/base/lib/nav-meta/index.js'), { resolveComponent: (exports) => exports.NavMeta }),
  'nav-toggle': loadable(() => import('@kickstartds/base/lib/nav-toggle/index.js'), { resolveComponent: (exports) => exports.NavToggle }),
  'picture': loadable(() => import('@kickstartds/base/lib/picture/index.js'), { resolveComponent: (exports) => exports.Picture }),
  'rich-text': loadable(() => import('@kickstartds/base/lib/rich-text/index.js'), { resolveComponent: (exports) => exports.RichText }),
  'section': loadable(() => import('@kickstartds/base/lib/section/index.js'), { resolveComponent: (exports) => exports.Section }),
  'slider': loadable(() => import('@kickstartds/base/lib/slider/index.js'), { resolveComponent: (exports) => exports.SlideContext }),
  'table': loadable(() => import('@kickstartds/base/lib/table/index.js'), { resolveComponent: (exports) => exports.Table }),
  'tag-label': loadable(() => import('@kickstartds/base/lib/tag-label/index.js'), { resolveComponent: (exports) => exports.TagLabel }),
  'tag-label-container': loadable(() => import('@kickstartds/base/lib/tag-label-container/index.js'), { resolveComponent: (exports) => exports.TagLabelContainer }),
  'teaser-box': loadable(() => import('@kickstartds/base/lib/teaser-box/index.js'), { resolveComponent: (exports) => exports.TeaserBox }),
  'teaser-row': loadable(() => import('@kickstartds/base/lib/teaser-row/index.js'), { resolveComponent: (exports) => exports.TeaserRow }),
  'text-media': loadable(() => import('@kickstartds/base/lib/text-media/index.js'), { resolveComponent: (exports) => exports.TextMedia }),
  'post-head': loadable(() => import('@kickstartds/blog/lib/post-head/index.js'), { resolveComponent: (exports) => exports.PostHead }),
  'post-teaser': loadable(() => import('@kickstartds/blog/lib/post-teaser/index.js'), { resolveComponent: (exports) => exports.PostTeaser }),
  'collapsible-box': loadable(() => import('@kickstartds/content/lib/collapsible-box/index.js'), { resolveComponent: (exports) => exports.CollapsibleBox }),
  'contact': loadable(() => import('@kickstartds/content/lib/contact/index.js'), { resolveComponent: (exports) => exports.Contact }),
  'count-up': loadable(() => import('@kickstartds/content/lib/count-up/index.js'), { resolveComponent: (exports) => exports.CountUp }),
  'logo-tiles': loadable(() => import('@kickstartds/content/lib/logo-tiles/index.js'), { resolveComponent: (exports) => exports.LogoTiles }),
  'quote': loadable(() => import('@kickstartds/content/lib/quote/index.js'), { resolveComponent: (exports) => exports.Quote }),
  'quotes-slider': loadable(() => import('@kickstartds/content/lib/quotes-slider/index.js'), { resolveComponent: (exports) => exports.QuotesSlider }),
  'storytelling': loadable(() => import('@kickstartds/content/lib/storytelling/index.js'), { resolveComponent: (exports) => exports.Storytelling }),
  'visual': loadable(() => import('@kickstartds/content/lib/visual/index.js'), { resolveComponent: (exports) => exports.Visual }),
  'visual-slider': loadable(() => import('@kickstartds/content/lib/visual-slider/index.js'), { resolveComponent: (exports) => exports.VisualSlider }),
};
