import { graphql } from "gatsby";

// THIS FILE HAS BEEN AUTO-GENERATED BY "@kickstartds/graphql-cli-generate-fragments"
// DO NOT EDIT THIS FILE DIRECTLY

export const ButtonComponentFragment = graphql`fragment ButtonComponent on ButtonComponent {
  label__634c
  variant__c8d5
  size__1735
  className__f69c
  icon__b287 {
    ...IconComponentNoNesting
  }
  iconBefore__ce4f
  iconAfter__9214
  dataComponent__fb24
  fillAnimation__a843
  iconAnimation__a42f
  typeAttr__b95e
  value__ed44
  name__6a5d
  disabled__f1d0
  type
}
`

export const IconComponentFragment = graphql`fragment IconComponent on IconComponent {
  icon__dcfe
  role__ea32
  className__251a
  type
}
`

export const ContentBoxComponentFragment = graphql`fragment ContentBoxComponent on ContentBoxComponent {
  ratio__30c5
  alignement__7c67
  image__b7d7
  topic__ed87
  text__b5a1
  link__4433 {
    ...ContentBoxComponentLinkNoNesting
  }
  type
}
`

export const ContentBoxComponentLinkFragment = graphql`fragment ContentBoxComponentLink on ContentBoxComponentLink {
  enabled
}
`

export const DividerComponentFragment = graphql`fragment DividerComponent on DividerComponent {
  variant__fdb0
  type
}
`

export const HeadlineComponentFragment = graphql`fragment HeadlineComponent on HeadlineComponent {
  level__503c
  align__498d
  content__3cc5
  subheadline__aa93
  spaceAfter__6f7d
  pageHeader__5c3f
  type
}
`

export const LightboxLazyImageComponentFragment = graphql`fragment LightboxLazyImageComponent on LightboxLazyImageComponent {
  thumb__64b3
  image__0dd8
  width__5f4a
  height__eeb9
  zoomIcon__8de6
  caption__dc74
  hideCaption__668c
  gallery__d524
  id__5744
  class__b1f4
  type
}
`

export const LinkButtonComponentFragment = graphql`fragment LinkButtonComponent on LinkButtonComponent {
  label__b988
  variant__a43d
  size__942c
  className__8726
  icon__157f {
    ...IconComponentNoNesting
  }
  iconBefore__7991
  iconAfter__c8b6
  dataComponent__8d9e
  fillAnimation__2a89
  iconAnimation__9933
  href__11db
  newTab__dc35
  type
}
`

export const PictureComponentFragment = graphql`fragment PictureComponent on PictureComponent {
  src__197b
  srcSet__866d
  alt__1f75
  width__4691
  height__23ff
  className__a117
  id__9f67
  itemProp__ba17
  style__ccee
  objectFit__1269
  noscript__ec26
  lazy__55bf
  sources__a109 {
    ...PictureComponentSourcesNoNesting
  }
  pictureClassName__9f3e
  type
}
`

export const PictureComponentSourcesFragment = graphql`fragment PictureComponentSources on PictureComponentSources {
  srcSet
  media
  type
}
`

export const ContainerFragment = graphql`fragment Container on Container {
  width
  gutter
  mode
  content {
    ...QuotesSliderComponentNoNesting,
    ...LinkButtonComponentNoNesting,
    ...ToggleComponentNoNesting,
    ...ButtonComponentNoNesting,
    ...TagLabelComponentNoNesting,
    ...VisualComponentNoNesting,
    ...QuoteComponentNoNesting,
    ...VisualSliderComponentNoNesting,
    ...ContactComponentNoNesting,
    ...StorytellingComponentNoNesting,
    ...CollapsibleBoxComponentNoNesting,
    ...CountUpComponentNoNesting,
    ...ContentBoxComponentNoNesting,
    ...HeadlineComponentNoNesting,
    ...TextMediaComponentNoNesting,
    ...TeaserBoxComponentNoNesting,
    ...LogoTilesComponentNoNesting,
    ...TeaserRowComponentNoNesting
  }
}
`

export const QuotesSliderComponentFragment = graphql`fragment QuotesSliderComponent on QuotesSliderComponent {
  slides__d47f {
    ...QuoteComponentNoNesting
  }
  type
}
`

export const QuoteComponentFragment = graphql`fragment QuoteComponent on QuoteComponent {
  image__f09b
  text__b65e
  source__86ac
  date__3f4e
  type
}
`

export const ToggleComponentFragment = graphql`fragment ToggleComponent on ToggleComponent {
  id__788a
  name__f2d9
  checked__90a6
  disabled__d11c
  type
}
`

export const TagLabelComponentFragment = graphql`fragment TagLabelComponent on TagLabelComponent {
  label__7246
  size__d93f
  link__6ced
  removable__7eaf
  type
}
`

export const VisualComponentFragment = graphql`fragment VisualComponent on VisualComponent {
  height__f2ca
  media__8f99 {
    ...VisualComponentMediaNoNesting
  }
  overlay__6df1
  box__5bd7 {
    ...VisualComponentBoxNoNesting
  }
  backgroundColor__4ca8
  inbox__8206
  skipButton__bf9d
  className__d3dc
  type
}
`

export const VisualComponentMediaFragment = graphql`fragment VisualComponentMedia on VisualComponentMedia {
  mode
  image {
    ...VisualComponentMediaImageNoNesting
  }
  video {
    ...VisualComponentMediaVideoNoNesting
  }
}
`

export const VisualComponentMediaImageFragment = graphql`fragment VisualComponentMediaImage on VisualComponentMediaImage {
  srcMobile
  srcTablet
  srcDesktop
  indent
  alt
}
`

export const VisualComponentMediaVideoFragment = graphql`fragment VisualComponentMediaVideo on VisualComponentMediaVideo {
  srcMobile
  srcTablet
  srcDesktop
}
`

export const VisualComponentBoxFragment = graphql`fragment VisualComponentBox on VisualComponentBox {
  enabled
  headline
  text
  link {
    ...VisualComponentBoxLinkNoNesting
  }
  indent
  horizontal
  vertical
  background
}
`

export const VisualComponentBoxLinkFragment = graphql`fragment VisualComponentBoxLink on VisualComponentBoxLink {
  enabled
}
`

export const VisualSliderComponentFragment = graphql`fragment VisualSliderComponent on VisualSliderComponent {
  autoplay__e333
  slides__e195 {
    ...VisualSliderComponentSlidesNoNesting
  }
  type
}
`

export const VisualSliderComponentSlidesFragment = graphql`fragment VisualSliderComponentSlides on VisualSliderComponentSlides {
  height__f2ca
  media__8f99 {
    ...VisualSliderComponentSlidesMediaNoNesting
  }
  overlay__6df1
  box__5bd7 {
    ...VisualSliderComponentSlidesBoxNoNesting
  }
  backgroundColor__4ca8
  inbox__8206
  skipButton__bf9d
  className__d3dc
  type
  label
}
`

export const VisualSliderComponentSlidesMediaFragment = graphql`fragment VisualSliderComponentSlidesMedia on VisualSliderComponentSlidesMedia {
  mode
  image {
    ...VisualSliderComponentSlidesMediaImageNoNesting
  }
  video {
    ...VisualSliderComponentSlidesMediaVideoNoNesting
  }
}
`

export const VisualSliderComponentSlidesMediaImageFragment = graphql`fragment VisualSliderComponentSlidesMediaImage on VisualSliderComponentSlidesMediaImage {
  srcMobile
  srcTablet
  srcDesktop
  indent
  alt
}
`

export const VisualSliderComponentSlidesMediaVideoFragment = graphql`fragment VisualSliderComponentSlidesMediaVideo on VisualSliderComponentSlidesMediaVideo {
  srcMobile
  srcTablet
  srcDesktop
}
`

export const VisualSliderComponentSlidesBoxFragment = graphql`fragment VisualSliderComponentSlidesBox on VisualSliderComponentSlidesBox {
  enabled
  headline
  text
  link {
    ...VisualSliderComponentSlidesBoxLinkNoNesting
  }
  indent
  horizontal
  vertical
  background
}
`

export const VisualSliderComponentSlidesBoxLinkFragment = graphql`fragment VisualSliderComponentSlidesBoxLink on VisualSliderComponentSlidesBoxLink {
  enabled
}
`

export const ContactComponentFragment = graphql`fragment ContactComponent on ContactComponent {
  image__a463 {
    ...PictureComponentNoNesting
  }
  title__5426
  subtitle__92ac
  phone__520b
  email__70d5
  copy__cda3
  type
}
`

export const StorytellingComponentFragment = graphql`fragment StorytellingComponent on StorytellingComponent {
  backgroundImage__cb66
  backgroundColor__291a
  full__be79
  image__cc97 {
    ...StorytellingComponentImageNoNesting
  }
  box__5f7a {
    ...StorytellingComponentBoxNoNesting
  }
  type
}
`

export const StorytellingComponentImageFragment = graphql`fragment StorytellingComponentImage on StorytellingComponentImage {
  source
  ratio
  vAlign
  hAlign
  order {
    ...StorytellingComponentImageOrderNoNesting
  }
}
`

export const StorytellingComponentImageOrderFragment = graphql`fragment StorytellingComponentImageOrder on StorytellingComponentImageOrder {
  mobileImageLast
  desktopImageLast
}
`

export const StorytellingComponentBoxFragment = graphql`fragment StorytellingComponentBox on StorytellingComponentBox {
  headline {
    ...HeadlineComponentNoNesting
  }
  text
  textAlign
  textColor
  vAlign
  hAlign
  link {
    ...LinkButtonComponentNoNesting
  }
}
`

export const CollapsibleBoxComponentFragment = graphql`fragment CollapsibleBoxComponent on CollapsibleBoxComponent {
  summary__919d
  text__9abc
  type
}
`

export const CountUpComponentFragment = graphql`fragment CountUpComponent on CountUpComponent {
  to__fc5f
  icon__ed13 {
    ...IconComponentNoNesting
  }
  topic__b6c8
  text__0f41
  link__ac78 {
    ...LinkButtonComponentNoNesting
  }
  type
}
`

export const TextMediaComponentFragment = graphql`fragment TextMediaComponent on TextMediaComponent {
  text__117a
  mediaAlignment__0da3
  media__d3b5 {
    ...TextMediaComponentMedia0NoNesting,
    ...TextMediaComponentMedia1NoNesting,
    ...TextMediaComponentMedia2NoNesting
  }
  type
}
`

export const TextMediaComponentMedia0Fragment = graphql`fragment TextMediaComponentMedia0 on TextMediaComponentMedia0 {
  video {
    ...TextMediaComponentMedia0VideoNoNesting
  }
  full
}
`

export const TextMediaComponentMedia0VideoFragment = graphql`fragment TextMediaComponentMedia0Video on TextMediaComponentMedia0Video {
  src
  iframe
  title
  width
  height
}
`

export const TextMediaComponentMedia1Fragment = graphql`fragment TextMediaComponentMedia1 on TextMediaComponentMedia1 {
  image {
    ...PictureComponentNoNesting
  }
  full
}
`

export const TextMediaComponentMedia2Fragment = graphql`fragment TextMediaComponentMedia2 on TextMediaComponentMedia2 {
  lightboxImage {
    ...LightboxLazyImageComponentNoNesting
  }
  full
}
`

export const TeaserBoxComponentFragment = graphql`fragment TeaserBoxComponent on TeaserBoxComponent {
  topic__8a0d
  text__da70
  darkStyle__b59c
  link__884d {
    ...TeaserBoxComponentLinkNoNesting
  }
  image__5eb9
  ratio__d62c
  imageSpacing__2828
  type
}
`

export const TeaserBoxComponentLinkFragment = graphql`fragment TeaserBoxComponentLink on TeaserBoxComponentLink {
  hidden
}
`

export const LogoTilesComponentFragment = graphql`fragment LogoTilesComponent on LogoTilesComponent {
  logos__8ff6 {
    ...PictureComponentNoNesting
  }
  type
}
`

export const TeaserRowComponentFragment = graphql`fragment TeaserRowComponent on TeaserRowComponent {
  topic__eb4b
  text__003d
  darkStyle__4848
  link__2757 {
    ...TeaserRowComponentLinkNoNesting
  }
  type
}
`

export const TeaserRowComponentLinkFragment = graphql`fragment TeaserRowComponentLink on TeaserRowComponentLink {
  hidden
}
`

export const SectionComponentFragment = graphql`fragment SectionComponent on SectionComponent {
  width__c976
  gutter__7060
  mode__123d
  content__2cb4 {
    ...QuotesSliderComponentNoNesting,
    ...LinkButtonComponentNoNesting,
    ...ToggleComponentNoNesting,
    ...ButtonComponentNoNesting,
    ...TagLabelComponentNoNesting,
    ...VisualComponentNoNesting,
    ...QuoteComponentNoNesting,
    ...VisualSliderComponentNoNesting,
    ...ContactComponentNoNesting,
    ...StorytellingComponentNoNesting,
    ...CollapsibleBoxComponentNoNesting,
    ...CountUpComponentNoNesting,
    ...ContentBoxComponentNoNesting,
    ...HeadlineComponentNoNesting,
    ...TextMediaComponentNoNesting,
    ...TeaserBoxComponentNoNesting,
    ...LogoTilesComponentNoNesting,
    ...TeaserRowComponentNoNesting
  }
  background__44d0
  spaceBefore__8a4a
  spaceAfter__9774
  headline__77a3 {
    ...HeadlineComponentNoNesting
  }
}
`

export const SlideFragment = graphql`fragment Slide on Slide {
  slideComponent
  previewComponent
  previewLabel
}
`

export const SliderComponentFragment = graphql`fragment SliderComponent on SliderComponent {
  autoplay__5854
  className__6e21
  component__655b
  arrows__f98f
  type
}
`

export const TeaserComponentFragment = graphql`fragment TeaserComponent on TeaserComponent {
  topic__d049
  text__cc83
  darkStyle__d107
  link__a055 {
    ...TeaserComponentLinkNoNesting
  }
  type
}
`

export const TeaserComponentLinkFragment = graphql`fragment TeaserComponentLink on TeaserComponentLink {
  hidden
}
`

export const VisualSlidePreviewComponentFragment = graphql`fragment VisualSlidePreviewComponent on VisualSlidePreviewComponent {
  previewLabel__516c
  type
}
`


export const ButtonComponentNoNestingFragment = graphql`fragment ButtonComponentNoNesting on ButtonComponent {
  label__634c
  variant__c8d5
  size__1735
  className__f69c
  iconBefore__ce4f
  iconAfter__9214
  dataComponent__fb24
  fillAnimation__a843
  iconAnimation__a42f
  typeAttr__b95e
  value__ed44
  name__6a5d
  disabled__f1d0
  type
}
`

export const IconComponentNoNestingFragment = graphql`fragment IconComponentNoNesting on IconComponent {
  icon__dcfe
  role__ea32
  className__251a
  type
}
`

export const ContentBoxComponentNoNestingFragment = graphql`fragment ContentBoxComponentNoNesting on ContentBoxComponent {
  ratio__30c5
  alignement__7c67
  image__b7d7
  topic__ed87
  text__b5a1
  type
}
`

export const ContentBoxComponentLinkNoNestingFragment = graphql`fragment ContentBoxComponentLinkNoNesting on ContentBoxComponentLink {
  enabled
}
`

export const DividerComponentNoNestingFragment = graphql`fragment DividerComponentNoNesting on DividerComponent {
  variant__fdb0
  type
}
`

export const HeadlineComponentNoNestingFragment = graphql`fragment HeadlineComponentNoNesting on HeadlineComponent {
  level__503c
  align__498d
  content__3cc5
  subheadline__aa93
  spaceAfter__6f7d
  pageHeader__5c3f
  type
}
`

export const LightboxLazyImageComponentNoNestingFragment = graphql`fragment LightboxLazyImageComponentNoNesting on LightboxLazyImageComponent {
  thumb__64b3
  image__0dd8
  width__5f4a
  height__eeb9
  zoomIcon__8de6
  caption__dc74
  hideCaption__668c
  gallery__d524
  id__5744
  class__b1f4
  type
}
`

export const LinkButtonComponentNoNestingFragment = graphql`fragment LinkButtonComponentNoNesting on LinkButtonComponent {
  label__b988
  variant__a43d
  size__942c
  className__8726
  iconBefore__7991
  iconAfter__c8b6
  dataComponent__8d9e
  fillAnimation__2a89
  iconAnimation__9933
  href__11db
  newTab__dc35
  type
}
`

export const PictureComponentNoNestingFragment = graphql`fragment PictureComponentNoNesting on PictureComponent {
  src__197b
  srcSet__866d
  alt__1f75
  width__4691
  height__23ff
  className__a117
  id__9f67
  itemProp__ba17
  style__ccee
  objectFit__1269
  noscript__ec26
  lazy__55bf
  pictureClassName__9f3e
  type
}
`

export const PictureComponentSourcesNoNestingFragment = graphql`fragment PictureComponentSourcesNoNesting on PictureComponentSources {
  srcSet
  media
  type
}
`

export const ContainerNoNestingFragment = graphql`fragment ContainerNoNesting on Container {
  width
  gutter
  mode
}
`

export const QuotesSliderComponentNoNestingFragment = graphql`fragment QuotesSliderComponentNoNesting on QuotesSliderComponent {
  type
}
`

export const QuoteComponentNoNestingFragment = graphql`fragment QuoteComponentNoNesting on QuoteComponent {
  image__f09b
  text__b65e
  source__86ac
  date__3f4e
  type
}
`

export const ToggleComponentNoNestingFragment = graphql`fragment ToggleComponentNoNesting on ToggleComponent {
  id__788a
  name__f2d9
  checked__90a6
  disabled__d11c
  type
}
`

export const TagLabelComponentNoNestingFragment = graphql`fragment TagLabelComponentNoNesting on TagLabelComponent {
  label__7246
  size__d93f
  link__6ced
  removable__7eaf
  type
}
`

export const VisualComponentNoNestingFragment = graphql`fragment VisualComponentNoNesting on VisualComponent {
  height__f2ca
  overlay__6df1
  backgroundColor__4ca8
  inbox__8206
  skipButton__bf9d
  className__d3dc
  type
}
`

export const VisualComponentMediaNoNestingFragment = graphql`fragment VisualComponentMediaNoNesting on VisualComponentMedia {
  mode
}
`

export const VisualComponentMediaImageNoNestingFragment = graphql`fragment VisualComponentMediaImageNoNesting on VisualComponentMediaImage {
  srcMobile
  srcTablet
  srcDesktop
  indent
  alt
}
`

export const VisualComponentMediaVideoNoNestingFragment = graphql`fragment VisualComponentMediaVideoNoNesting on VisualComponentMediaVideo {
  srcMobile
  srcTablet
  srcDesktop
}
`

export const VisualComponentBoxNoNestingFragment = graphql`fragment VisualComponentBoxNoNesting on VisualComponentBox {
  enabled
  headline
  text
  indent
  horizontal
  vertical
  background
}
`

export const VisualComponentBoxLinkNoNestingFragment = graphql`fragment VisualComponentBoxLinkNoNesting on VisualComponentBoxLink {
  enabled
}
`

export const VisualSliderComponentNoNestingFragment = graphql`fragment VisualSliderComponentNoNesting on VisualSliderComponent {
  autoplay__e333
  type
}
`

export const VisualSliderComponentSlidesNoNestingFragment = graphql`fragment VisualSliderComponentSlidesNoNesting on VisualSliderComponentSlides {
  height__f2ca
  overlay__6df1
  backgroundColor__4ca8
  inbox__8206
  skipButton__bf9d
  className__d3dc
  type
  label
}
`

export const VisualSliderComponentSlidesMediaNoNestingFragment = graphql`fragment VisualSliderComponentSlidesMediaNoNesting on VisualSliderComponentSlidesMedia {
  mode
}
`

export const VisualSliderComponentSlidesMediaImageNoNestingFragment = graphql`fragment VisualSliderComponentSlidesMediaImageNoNesting on VisualSliderComponentSlidesMediaImage {
  srcMobile
  srcTablet
  srcDesktop
  indent
  alt
}
`

export const VisualSliderComponentSlidesMediaVideoNoNestingFragment = graphql`fragment VisualSliderComponentSlidesMediaVideoNoNesting on VisualSliderComponentSlidesMediaVideo {
  srcMobile
  srcTablet
  srcDesktop
}
`

export const VisualSliderComponentSlidesBoxNoNestingFragment = graphql`fragment VisualSliderComponentSlidesBoxNoNesting on VisualSliderComponentSlidesBox {
  enabled
  headline
  text
  indent
  horizontal
  vertical
  background
}
`

export const VisualSliderComponentSlidesBoxLinkNoNestingFragment = graphql`fragment VisualSliderComponentSlidesBoxLinkNoNesting on VisualSliderComponentSlidesBoxLink {
  enabled
}
`

export const ContactComponentNoNestingFragment = graphql`fragment ContactComponentNoNesting on ContactComponent {
  title__5426
  subtitle__92ac
  phone__520b
  email__70d5
  copy__cda3
  type
}
`

export const StorytellingComponentNoNestingFragment = graphql`fragment StorytellingComponentNoNesting on StorytellingComponent {
  backgroundImage__cb66
  backgroundColor__291a
  full__be79
  type
}
`

export const StorytellingComponentImageNoNestingFragment = graphql`fragment StorytellingComponentImageNoNesting on StorytellingComponentImage {
  source
  ratio
  vAlign
  hAlign
}
`

export const StorytellingComponentImageOrderNoNestingFragment = graphql`fragment StorytellingComponentImageOrderNoNesting on StorytellingComponentImageOrder {
  mobileImageLast
  desktopImageLast
}
`

export const StorytellingComponentBoxNoNestingFragment = graphql`fragment StorytellingComponentBoxNoNesting on StorytellingComponentBox {
  text
  textAlign
  textColor
  vAlign
  hAlign
}
`

export const CollapsibleBoxComponentNoNestingFragment = graphql`fragment CollapsibleBoxComponentNoNesting on CollapsibleBoxComponent {
  summary__919d
  text__9abc
  type
}
`

export const CountUpComponentNoNestingFragment = graphql`fragment CountUpComponentNoNesting on CountUpComponent {
  to__fc5f
  topic__b6c8
  text__0f41
  type
}
`

export const TextMediaComponentNoNestingFragment = graphql`fragment TextMediaComponentNoNesting on TextMediaComponent {
  text__117a
  mediaAlignment__0da3
  type
}
`

export const TextMediaComponentMedia0NoNestingFragment = graphql`fragment TextMediaComponentMedia0NoNesting on TextMediaComponentMedia0 {
  full
}
`

export const TextMediaComponentMedia0VideoNoNestingFragment = graphql`fragment TextMediaComponentMedia0VideoNoNesting on TextMediaComponentMedia0Video {
  src
  iframe
  title
  width
  height
}
`

export const TextMediaComponentMedia1NoNestingFragment = graphql`fragment TextMediaComponentMedia1NoNesting on TextMediaComponentMedia1 {
  full
}
`

export const TextMediaComponentMedia2NoNestingFragment = graphql`fragment TextMediaComponentMedia2NoNesting on TextMediaComponentMedia2 {
  full
}
`

export const TeaserBoxComponentNoNestingFragment = graphql`fragment TeaserBoxComponentNoNesting on TeaserBoxComponent {
  topic__8a0d
  text__da70
  darkStyle__b59c
  image__5eb9
  ratio__d62c
  imageSpacing__2828
  type
}
`

export const TeaserBoxComponentLinkNoNestingFragment = graphql`fragment TeaserBoxComponentLinkNoNesting on TeaserBoxComponentLink {
  hidden
}
`

export const LogoTilesComponentNoNestingFragment = graphql`fragment LogoTilesComponentNoNesting on LogoTilesComponent {
  type
}
`

export const TeaserRowComponentNoNestingFragment = graphql`fragment TeaserRowComponentNoNesting on TeaserRowComponent {
  topic__eb4b
  text__003d
  darkStyle__4848
  type
}
`

export const TeaserRowComponentLinkNoNestingFragment = graphql`fragment TeaserRowComponentLinkNoNesting on TeaserRowComponentLink {
  hidden
}
`

export const SectionComponentNoNestingFragment = graphql`fragment SectionComponentNoNesting on SectionComponent {
  width__c976
  gutter__7060
  mode__123d
  background__44d0
  spaceBefore__8a4a
  spaceAfter__9774
}
`

export const SlideNoNestingFragment = graphql`fragment SlideNoNesting on Slide {
  slideComponent
  previewComponent
  previewLabel
}
`

export const SliderComponentNoNestingFragment = graphql`fragment SliderComponentNoNesting on SliderComponent {
  autoplay__5854
  className__6e21
  component__655b
  arrows__f98f
  type
}
`

export const TeaserComponentNoNestingFragment = graphql`fragment TeaserComponentNoNesting on TeaserComponent {
  topic__d049
  text__cc83
  darkStyle__d107
  type
}
`

export const TeaserComponentLinkNoNestingFragment = graphql`fragment TeaserComponentLinkNoNesting on TeaserComponentLink {
  hidden
}
`

export const VisualSlidePreviewComponentNoNestingFragment = graphql`fragment VisualSlidePreviewComponentNoNesting on VisualSlidePreviewComponent {
  previewLabel__516c
  type
}
`


export const ButtonComponentDeepNestingFragment = graphql`fragment ButtonComponentDeepNesting on ButtonComponent {
  label__634c
  variant__c8d5
  size__1735
  className__f69c
  icon__b287 {
    ...IconComponentDeepNesting
  }
  iconBefore__ce4f
  iconAfter__9214
  dataComponent__fb24
  fillAnimation__a843
  iconAnimation__a42f
  typeAttr__b95e
  value__ed44
  name__6a5d
  disabled__f1d0
  type
}
`

export const IconComponentDeepNestingFragment = graphql`fragment IconComponentDeepNesting on IconComponent {
  icon__dcfe
  role__ea32
  className__251a
  type
}
`

export const ContentBoxComponentDeepNestingFragment = graphql`fragment ContentBoxComponentDeepNesting on ContentBoxComponent {
  ratio__30c5
  alignement__7c67
  image__b7d7
  topic__ed87
  text__b5a1
  link__4433 {
    ...ContentBoxComponentLinkDeepNesting
  }
  type
}
`

export const ContentBoxComponentLinkDeepNestingFragment = graphql`fragment ContentBoxComponentLinkDeepNesting on ContentBoxComponentLink {
  enabled
}
`

export const DividerComponentDeepNestingFragment = graphql`fragment DividerComponentDeepNesting on DividerComponent {
  variant__fdb0
  type
}
`

export const HeadlineComponentDeepNestingFragment = graphql`fragment HeadlineComponentDeepNesting on HeadlineComponent {
  level__503c
  align__498d
  content__3cc5
  subheadline__aa93
  spaceAfter__6f7d
  pageHeader__5c3f
  type
}
`

export const LightboxLazyImageComponentDeepNestingFragment = graphql`fragment LightboxLazyImageComponentDeepNesting on LightboxLazyImageComponent {
  thumb__64b3
  image__0dd8
  width__5f4a
  height__eeb9
  zoomIcon__8de6
  caption__dc74
  hideCaption__668c
  gallery__d524
  id__5744
  class__b1f4
  type
}
`

export const LinkButtonComponentDeepNestingFragment = graphql`fragment LinkButtonComponentDeepNesting on LinkButtonComponent {
  label__b988
  variant__a43d
  size__942c
  className__8726
  icon__157f {
    ...IconComponentDeepNesting
  }
  iconBefore__7991
  iconAfter__c8b6
  dataComponent__8d9e
  fillAnimation__2a89
  iconAnimation__9933
  href__11db
  newTab__dc35
  type
}
`

export const PictureComponentDeepNestingFragment = graphql`fragment PictureComponentDeepNesting on PictureComponent {
  src__197b
  srcSet__866d
  alt__1f75
  width__4691
  height__23ff
  className__a117
  id__9f67
  itemProp__ba17
  style__ccee
  objectFit__1269
  noscript__ec26
  lazy__55bf
  sources__a109 {
    ...PictureComponentSourcesDeepNesting
  }
  pictureClassName__9f3e
  type
}
`

export const PictureComponentSourcesDeepNestingFragment = graphql`fragment PictureComponentSourcesDeepNesting on PictureComponentSources {
  srcSet
  media
  type
}
`

export const ContainerDeepNestingFragment = graphql`fragment ContainerDeepNesting on Container {
  width
  gutter
  mode
  content {
    ...QuotesSliderComponentDeepNesting,
    ...LinkButtonComponentDeepNesting,
    ...ToggleComponentDeepNesting,
    ...ButtonComponentDeepNesting,
    ...TagLabelComponentDeepNesting,
    ...VisualComponentDeepNesting,
    ...QuoteComponentDeepNesting,
    ...VisualSliderComponentDeepNesting,
    ...ContactComponentDeepNesting,
    ...StorytellingComponentDeepNesting,
    ...CollapsibleBoxComponentDeepNesting,
    ...CountUpComponentDeepNesting,
    ...ContentBoxComponentDeepNesting,
    ...HeadlineComponentDeepNesting,
    ...TextMediaComponentDeepNesting,
    ...TeaserBoxComponentDeepNesting,
    ...LogoTilesComponentDeepNesting,
    ...TeaserRowComponentDeepNesting
  }
}
`

export const QuotesSliderComponentDeepNestingFragment = graphql`fragment QuotesSliderComponentDeepNesting on QuotesSliderComponent {
  slides__d47f {
    ...QuoteComponentDeepNesting
  }
  type
}
`

export const QuoteComponentDeepNestingFragment = graphql`fragment QuoteComponentDeepNesting on QuoteComponent {
  image__f09b
  text__b65e
  source__86ac
  date__3f4e
  type
}
`

export const ToggleComponentDeepNestingFragment = graphql`fragment ToggleComponentDeepNesting on ToggleComponent {
  id__788a
  name__f2d9
  checked__90a6
  disabled__d11c
  type
}
`

export const TagLabelComponentDeepNestingFragment = graphql`fragment TagLabelComponentDeepNesting on TagLabelComponent {
  label__7246
  size__d93f
  link__6ced
  removable__7eaf
  type
}
`

export const VisualComponentDeepNestingFragment = graphql`fragment VisualComponentDeepNesting on VisualComponent {
  height__f2ca
  media__8f99 {
    ...VisualComponentMediaDeepNesting
  }
  overlay__6df1
  box__5bd7 {
    ...VisualComponentBoxDeepNesting
  }
  backgroundColor__4ca8
  inbox__8206
  skipButton__bf9d
  className__d3dc
  type
}
`

export const VisualComponentMediaDeepNestingFragment = graphql`fragment VisualComponentMediaDeepNesting on VisualComponentMedia {
  mode
  image {
    ...VisualComponentMediaImageDeepNesting
  }
  video {
    ...VisualComponentMediaVideoDeepNesting
  }
}
`

export const VisualComponentMediaImageDeepNestingFragment = graphql`fragment VisualComponentMediaImageDeepNesting on VisualComponentMediaImage {
  srcMobile
  srcTablet
  srcDesktop
  indent
  alt
}
`

export const VisualComponentMediaVideoDeepNestingFragment = graphql`fragment VisualComponentMediaVideoDeepNesting on VisualComponentMediaVideo {
  srcMobile
  srcTablet
  srcDesktop
}
`

export const VisualComponentBoxDeepNestingFragment = graphql`fragment VisualComponentBoxDeepNesting on VisualComponentBox {
  enabled
  headline
  text
  link {
    ...VisualComponentBoxLinkDeepNesting
  }
  indent
  horizontal
  vertical
  background
}
`

export const VisualComponentBoxLinkDeepNestingFragment = graphql`fragment VisualComponentBoxLinkDeepNesting on VisualComponentBoxLink {
  enabled
}
`

export const VisualSliderComponentDeepNestingFragment = graphql`fragment VisualSliderComponentDeepNesting on VisualSliderComponent {
  autoplay__e333
  slides__e195 {
    ...VisualSliderComponentSlidesDeepNesting
  }
  type
}
`

export const VisualSliderComponentSlidesDeepNestingFragment = graphql`fragment VisualSliderComponentSlidesDeepNesting on VisualSliderComponentSlides {
  height__f2ca
  media__8f99 {
    ...VisualSliderComponentSlidesMediaDeepNesting
  }
  overlay__6df1
  box__5bd7 {
    ...VisualSliderComponentSlidesBoxDeepNesting
  }
  backgroundColor__4ca8
  inbox__8206
  skipButton__bf9d
  className__d3dc
  type
  label
}
`

export const VisualSliderComponentSlidesMediaDeepNestingFragment = graphql`fragment VisualSliderComponentSlidesMediaDeepNesting on VisualSliderComponentSlidesMedia {
  mode
  image {
    ...VisualSliderComponentSlidesMediaImageDeepNesting
  }
  video {
    ...VisualSliderComponentSlidesMediaVideoDeepNesting
  }
}
`

export const VisualSliderComponentSlidesMediaImageDeepNestingFragment = graphql`fragment VisualSliderComponentSlidesMediaImageDeepNesting on VisualSliderComponentSlidesMediaImage {
  srcMobile
  srcTablet
  srcDesktop
  indent
  alt
}
`

export const VisualSliderComponentSlidesMediaVideoDeepNestingFragment = graphql`fragment VisualSliderComponentSlidesMediaVideoDeepNesting on VisualSliderComponentSlidesMediaVideo {
  srcMobile
  srcTablet
  srcDesktop
}
`

export const VisualSliderComponentSlidesBoxDeepNestingFragment = graphql`fragment VisualSliderComponentSlidesBoxDeepNesting on VisualSliderComponentSlidesBox {
  enabled
  headline
  text
  link {
    ...VisualSliderComponentSlidesBoxLinkDeepNesting
  }
  indent
  horizontal
  vertical
  background
}
`

export const VisualSliderComponentSlidesBoxLinkDeepNestingFragment = graphql`fragment VisualSliderComponentSlidesBoxLinkDeepNesting on VisualSliderComponentSlidesBoxLink {
  enabled
}
`

export const ContactComponentDeepNestingFragment = graphql`fragment ContactComponentDeepNesting on ContactComponent {
  image__a463 {
    ...PictureComponentDeepNesting
  }
  title__5426
  subtitle__92ac
  phone__520b
  email__70d5
  copy__cda3
  type
}
`

export const StorytellingComponentDeepNestingFragment = graphql`fragment StorytellingComponentDeepNesting on StorytellingComponent {
  backgroundImage__cb66
  backgroundColor__291a
  full__be79
  image__cc97 {
    ...StorytellingComponentImageDeepNesting
  }
  box__5f7a {
    ...StorytellingComponentBoxDeepNesting
  }
  type
}
`

export const StorytellingComponentImageDeepNestingFragment = graphql`fragment StorytellingComponentImageDeepNesting on StorytellingComponentImage {
  source
  ratio
  vAlign
  hAlign
  order {
    ...StorytellingComponentImageOrderDeepNesting
  }
}
`

export const StorytellingComponentImageOrderDeepNestingFragment = graphql`fragment StorytellingComponentImageOrderDeepNesting on StorytellingComponentImageOrder {
  mobileImageLast
  desktopImageLast
}
`

export const StorytellingComponentBoxDeepNestingFragment = graphql`fragment StorytellingComponentBoxDeepNesting on StorytellingComponentBox {
  headline {
    ...HeadlineComponentDeepNesting
  }
  text
  textAlign
  textColor
  vAlign
  hAlign
  link {
    ...LinkButtonComponentDeepNesting
  }
}
`

export const CollapsibleBoxComponentDeepNestingFragment = graphql`fragment CollapsibleBoxComponentDeepNesting on CollapsibleBoxComponent {
  summary__919d
  text__9abc
  type
}
`

export const CountUpComponentDeepNestingFragment = graphql`fragment CountUpComponentDeepNesting on CountUpComponent {
  to__fc5f
  icon__ed13 {
    ...IconComponentDeepNesting
  }
  topic__b6c8
  text__0f41
  link__ac78 {
    ...LinkButtonComponentDeepNesting
  }
  type
}
`

export const TextMediaComponentDeepNestingFragment = graphql`fragment TextMediaComponentDeepNesting on TextMediaComponent {
  text__117a
  mediaAlignment__0da3
  media__d3b5 {
    ...TextMediaComponentMedia0DeepNesting,
    ...TextMediaComponentMedia1DeepNesting,
    ...TextMediaComponentMedia2DeepNesting
  }
  type
}
`

export const TextMediaComponentMedia0DeepNestingFragment = graphql`fragment TextMediaComponentMedia0DeepNesting on TextMediaComponentMedia0 {
  video {
    ...TextMediaComponentMedia0VideoDeepNesting
  }
  full
}
`

export const TextMediaComponentMedia0VideoDeepNestingFragment = graphql`fragment TextMediaComponentMedia0VideoDeepNesting on TextMediaComponentMedia0Video {
  src
  iframe
  title
  width
  height
}
`

export const TextMediaComponentMedia1DeepNestingFragment = graphql`fragment TextMediaComponentMedia1DeepNesting on TextMediaComponentMedia1 {
  image {
    ...PictureComponentDeepNesting
  }
  full
}
`

export const TextMediaComponentMedia2DeepNestingFragment = graphql`fragment TextMediaComponentMedia2DeepNesting on TextMediaComponentMedia2 {
  lightboxImage {
    ...LightboxLazyImageComponentDeepNesting
  }
  full
}
`

export const TeaserBoxComponentDeepNestingFragment = graphql`fragment TeaserBoxComponentDeepNesting on TeaserBoxComponent {
  topic__8a0d
  text__da70
  darkStyle__b59c
  link__884d {
    ...TeaserBoxComponentLinkDeepNesting
  }
  image__5eb9
  ratio__d62c
  imageSpacing__2828
  type
}
`

export const TeaserBoxComponentLinkDeepNestingFragment = graphql`fragment TeaserBoxComponentLinkDeepNesting on TeaserBoxComponentLink {
  hidden
}
`

export const LogoTilesComponentDeepNestingFragment = graphql`fragment LogoTilesComponentDeepNesting on LogoTilesComponent {
  logos__8ff6 {
    ...PictureComponentDeepNesting
  }
  type
}
`

export const TeaserRowComponentDeepNestingFragment = graphql`fragment TeaserRowComponentDeepNesting on TeaserRowComponent {
  topic__eb4b
  text__003d
  darkStyle__4848
  link__2757 {
    ...TeaserRowComponentLinkDeepNesting
  }
  type
}
`

export const TeaserRowComponentLinkDeepNestingFragment = graphql`fragment TeaserRowComponentLinkDeepNesting on TeaserRowComponentLink {
  hidden
}
`

export const SectionComponentDeepNestingFragment = graphql`fragment SectionComponentDeepNesting on SectionComponent {
  width__c976
  gutter__7060
  mode__123d
  content__2cb4 {
    ...QuotesSliderComponentDeepNesting,
    ...LinkButtonComponentDeepNesting,
    ...ToggleComponentDeepNesting,
    ...ButtonComponentDeepNesting,
    ...TagLabelComponentDeepNesting,
    ...VisualComponentDeepNesting,
    ...QuoteComponentDeepNesting,
    ...VisualSliderComponentDeepNesting,
    ...ContactComponentDeepNesting,
    ...StorytellingComponentDeepNesting,
    ...CollapsibleBoxComponentDeepNesting,
    ...CountUpComponentDeepNesting,
    ...ContentBoxComponentDeepNesting,
    ...HeadlineComponentDeepNesting,
    ...TextMediaComponentDeepNesting,
    ...TeaserBoxComponentDeepNesting,
    ...LogoTilesComponentDeepNesting,
    ...TeaserRowComponentDeepNesting
  }
  background__44d0
  spaceBefore__8a4a
  spaceAfter__9774
  headline__77a3 {
    ...HeadlineComponentDeepNesting
  }
}
`

export const SlideDeepNestingFragment = graphql`fragment SlideDeepNesting on Slide {
  slideComponent
  previewComponent
  previewLabel
}
`

export const SliderComponentDeepNestingFragment = graphql`fragment SliderComponentDeepNesting on SliderComponent {
  autoplay__5854
  className__6e21
  component__655b
  arrows__f98f
  type
}
`

export const TeaserComponentDeepNestingFragment = graphql`fragment TeaserComponentDeepNesting on TeaserComponent {
  topic__d049
  text__cc83
  darkStyle__d107
  link__a055 {
    ...TeaserComponentLinkDeepNesting
  }
  type
}
`

export const TeaserComponentLinkDeepNestingFragment = graphql`fragment TeaserComponentLinkDeepNesting on TeaserComponentLink {
  hidden
}
`

export const VisualSlidePreviewComponentDeepNestingFragment = graphql`fragment VisualSlidePreviewComponentDeepNesting on VisualSlidePreviewComponent {
  previewLabel__516c
  type
}
`



